modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT Licence"

[[mods]]
modId="detailab"
version="${file.jarVersion}"
displayName="细节盔甲条：重装"
logoFile="icon.png"
authors="RedLime"
credits="snessim, Heamaci, Autovw, 木板"
description='''细节盔甲条的1.20.1重制升级版'''

[[dependencies.detailab]]
    modId="forge"
    mandatory=true
    # setting the minimum comaptible Forge version to 41.0.94 due to incompatibility with previous versions
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.detailab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="CLIENT"
