modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT Licence"

[[mods]]
modId="detailab"
version="${file.jarVersion}"
displayName="Detail Armor Bar"
logoFile="icon.png"
authors="RedLime"
credits="snessim, Heamaci, Autovw"
description='''Show more details of armors in Armor bar!'''
displayURL="https://github.com/RedLime/DetailArmorBar/tree/1.19-forge"

[[dependencies.detailab]]
    modId="forge"
    mandatory=true
    # setting the minimum comaptible Forge version to 41.0.94 due to incompatibility with previous versions
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.detailab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="CLIENT"
